common/urls.py
from django.urls import path
from . import views

app_name = 'common'

urlpatterns = [
    path('',views.index,name='index'),
    path('profile',views.profile,name='profile'),
    path('logout',views.logout,name='logout')

]

resort/urls.py
from django.contrib import admin
from django.urls import include , path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('common.urls')),
    path('resort_admin/',include('resort_admin.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

resort_admin/urls.py
from django.urls import path
from . import views
app_name = 'resort_admin'

urlpatterns = [
    path('admin_master',views.admin_master,name='admin_master'),
    path('add_room',views.add_room,name='add_room'),
    path('staff_details',views.staff_details,name='staff_details'),
    path('add_staff',views.add_staff,name='add_staff'),
    path('room_details',views.room_details,name='room_details'),
    path('',views.admin_login,name='admin_login'),
    path('delete_room/<int:room_id>',views.delete_room,name='delete_room'),
    path('room_book',views.room_book,name='room_book'),
    # path('delete_book',views.delete_book,name='delete_book')
    ]

common/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    add_review = models.CharField(max_length=500)
    
class Customer(models.Model):
    customer_username = models.CharField(max_length=50)
    customer_email = models.CharField(max_length=50)
    customer_password = models.CharField(max_length=50)
    
class Bookroom(models.Model):
    book_name = models.CharField(max_length=100)
    book_email = models.CharField(max_length=100)
    check_in = models.CharField(max_length=50)
    check_out = models.CharField(max_length=50)
    

resort_admin/models.py
from django.db import models

# Create your models here.
class Resort_admin(models.Model):
    user_name = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    
class Add_room(models.Model):
    room_name = models.CharField(max_length=50)
    room_capacity = models.CharField(max_length=50)
    room_photo = models.ImageField(upload_to = 'room/')
    room_price = models.CharField(max_length=100)
    room_description = models.CharField(max_length=1000)
    
class Staff(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    aadhaar_card = models.CharField(max_length=50)
    Qualification = models.CharField(max_length=50)
    agg = models.CharField(max_length=50)
    photo = models.ImageField(upload_to='staff/')

common/views.py
from django.shortcuts import render,redirect
from common.models import Bookroom, Customer, Review

from resort_admin.models import Add_room

def index(request):
    # profile_list = Customer.objects.get(id = request.session['customer'])
    rewiew_list = Review.objects.all()
    room_list = Add_room.objects.all()
    msg = ""
    if request.method == 'POST':
        if 'add_review' in request.POST:
            add_review = request.POST['review']
            newreview = Review(
                add_review = add_review
            )
            newreview.save()
        if 'registration' in request.POST:
            customer_username = request.POST['customer_username']
            customer_email = request.POST['customer_email']
            customer_password = request.POST['customer_password']
            newcustomer = Customer(
                customer_username = customer_username,
                customer_email = customer_email,
                customer_password = customer_password
            )
            newcustomer.save()
        if 'bookroom' in request.POST:
            book_name = request.POST['book_name']
            book_email = request.POST['book_email']
            check_in = request.POST['check_in']
            check_out = request.POST['check_out']
            newbookroom = Bookroom(
                book_name = book_name,
                book_email = book_email,
                check_in = check_in,
                check_out = check_out,
            )
            newbookroom.save()
        if 'login' in request.POST:
            login_name = request.POST['login_name']
            login_password = request.POST['login_password']
            try :
                customerlog = Customer.objects.get(
                    customer_username = login_name,
                    customer_password = login_password
                    )
                request.session['customer'] = customerlog.id
                return redirect ('common:index')
            except :
                msg = 'invalid password or username'
   
    return render(request,'index.html',{ 'reviews' : rewiew_list , 'room_lists' : room_list , 'msg' : msg })

def profile(request):
    profile_list = Customer.objects.get( id = request.session['customer'] )
    return render (request,'profile.html',{ 'profile' : profile_list })

def logout(request):
    del request.session['customer']
    return redirect('common:index')



# Create your views here.

resort_admin/views.py
from django.shortcuts import render,redirect
from common.models import Bookroom

from resort_admin.models import Add_room, Resort_admin

def admin_master(request):
    return render(request,'admin_template/admin_master.html')

def add_room(request):
    if request.method == 'POST':
        room_name = request.POST['room_name']
        room_capacity = request.POST['room_capacity']
        room_photo = request.FILES['room_photo']
        room_price = request.POST['room_price']
        room_description = request.POST['room_description']
        new_room = Add_room(
            room_name = room_name,
            room_capacity = room_capacity,
            room_photo = room_photo,
            room_price = room_price,
            room_description = room_description,
        )
        new_room.save()
        
    return render(request,'admin_template/add_room.html')

def room_details(request):
    room_details = Add_room.objects.all()
    
    return render(request,'admin_template/room_details.html', { 'room' : room_details })

def staff_details(request):
    return render(request,'admin_template/staff_details.html')

def add_staff(request):
    return render(request,'admin_template/add_staff.html')

def admin_login(request):
    msg = ''
    if request.method == 'POST':
        user_name = request.POST['username']
        password = request.POST['password']
        try :
            resort_admin = Resort_admin.objects.get(
                user_name = user_name,
                password = password,
                )
            request.session['resort_admin'] = resort_admin.id
            return redirect ('resort_admin:admin_master')
        except :
            msg = 'invalid password or username'
    return render(request,'admin_template/admin_login.html',{ 'msg' : msg })

def delete_room(request,room_id):
    delete_rooms = Add_room.objects.get(
        id = room_id
    )
    delete_rooms.delete()
    return redirect('resort_admin:room_details')

# def delete_book(request,book_id):
#     delete_books = Bookroom.objects.get(
#         id = book_id
#     )
#     delete_books.delete()
#     return redirect('Resort_admin:room_book')

def room_book(request):
    room_book = Bookroom.objects.all()
    return render(request,'admin_template/room_book.html',{ 'room_book' : room_book })


    


# Create your views here.

common/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
    <title>profile</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h1 id="profile-name" >profile</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6"  id="name-bar">
                <h1 class="profile-name">{{profile.customer_username}}</h1>
                <h1 class="profile-name">{{ profile.customer_email }}</h1>
            </div>
        </div>
    </div>
</body>
</html>

resort_admin/templates/admin_template/add_room.html
{% extends 'admin_template/admin_master.html' %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card m-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Add room</h5>
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label class="form-label">Name</label>
                            <input type="text" class="form-control" name="room_name">
                        </div>
                        <div class="mb-3">
                            <select class="form-select" aria-label="Default select example" name="room_capacity">
                                <option selected>Room capacity</option>
                                <option value="1">Adult 1</option>
                                <option value="2">Adult 2</option>
                                <option value="3">Adult 3</option>
                              </select>
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Photo</label>
                            <input type="file" class="form-control" name="room_photo">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Price</label>
                            <input type="number" class="form-control" name="room_price">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Description</label>
                            <input type="text" class="form-control" name="room_description">
                        </div>
                        <div class="mb-3 text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock %}

resort_admin/templates/admin_template/add_staff.html
{% extends 'admin_template/admin_master.html' %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="card m-5">
                <div class="card-body">
                    <h5 class="card-title text-center">Add Staff</h5>
                    <form>
                        <div class="mb-3">
                            <label class="form-label">First Name</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Last name</label>
                            <input type="text" class="form-control">
                        </div><div class="mb-3">
                            <label class="form-label">Address</label>
                            <input type="text" class="form-control">
                        </div>                       
                        <div class="mb-3">
                            <label class="form-label">aadhaar card number</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Qualification</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Age</label>
                            <input type="number" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Photo</label>
                            <input type="file" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Staff Id</label>
                            <input type="number" class="form-control">
                        </div>
                        <div class="mb-3 text-center">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                        
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock  %}

resort_admin/templates/admin_template/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="row p-5">
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title text-center">Admin Login</h3>
                        {{ msg }}
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label class="form-label" >User Name</label>
                                <input type="text" class="form-control" name='username'>
                            </div>
                            <div class="mb-3">
                                <label class="form-label" >Password</label>
                                <input type="password" class="form-control" name='password'>
                            </div>
                            <div class="mb-3 text-center">
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4"></div>
        </div>
    </div>
</body>

</html>

resort_admin/templates/admin_template/admin_master.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <style>
            body{
                overflow-x: hidden;
            }
        </style>

</head>

<body class="bg-light">
    <nav class="navbar navbar-expand-lg bg-white p-4">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container-flex">
        <div class="row">
            <div class="col-md-3">
                <nav class="nav flex-column">
                    <div class="p-5 fs-2" style="border: 1px solid blue; height: 27em;">
                        <a class="nav-link" href="{% url 'resort_admin:admin_master' %}">Home</a>                        <a class="nav-link" href="{% url 'resort_admin:add_room' %}">Add room</a>
                        <a class="nav-link" href="{% url 'resort_admin:room_details' %}">Room details</a>
                        <a class="nav-link" href="{% url 'resort_admin:staff_details' %}">Staff details</a>
                        <a class="nav-link" href="{% url 'resort_admin:add_staff' %}">Add Staff</a>
                        <a class="nav-link" href="{% url 'resort_admin:room_book' %}">bookroom</a>
                    </div>
                </nav>
            </div>
            <div class="col-md-9">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>




</body>

</html>

resort_admin/templates/admin_template/room_book.html
{% extends 'admin_template/admin_master.html' %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <table class="table border-primary">
            <thead>
                <tr>
                    <th scope="col">No</th>
                    <th scope="col">room Name</th>
                    <th scope="col">email</th>
                    <th scope="col">check_in</th>
                    <th scope="col">check_out</th>
                    <!-- <th scope="col">description</th> -->
                    <th scope="col">remove</th>
                </tr>
            </thead>
            {% for book in room_book %}
            <tbody>
                <td>{{ book.id }}</td>
                <td>{{ book.book_name }}</td>
                <td>{{ book.book_email }}</td>
                <td>{{ book.check_in }}</td>
                <td>{{ book.check_out }}</td>
        
            </tbody>
            {% endfor %}

    </div>
</div>

{% endblock %}

resort_admin/templates/admin_template/room_details.html
{% extends 'admin_template/admin_master.html' %}
{% block content %}
{% load static %}
<div class="container">
    <div class="row">
        <table class="table border-primary">
            <thead>
              <tr>
                <th scope="col">No</th>
                <th scope="col">Name</th>
                <th scope="col">capacity</th>
                <th scope="col">photo</th>
                <th scope="col">price</th>
                <!-- <th scope="col">description</th> -->
                <th scope="col">remove</th>
              </tr>
            </thead>
            {% for rooms in room %}
            <tbody>
                <td>{{ rooms.id }}</td>
                <td>{{ rooms.room_name }}</td>
                <td>{{ rooms.room_capacity }}</td>
                <td>{{ rooms.room_photo }}</td>
                <td>{{ rooms.room_price }}</td>
                <td>{{ rooms.room_description }}</td>
                <td>
                    <a href="{% url 'resort_admin:delete_room' rooms.id %}"><button type="button" class="btn btn-primary">Delete</button></a>
                </td>
            </tbody>
            {% endfor %}
              
    </div>
</div>

{% endblock  %}

resort_admin/templates/admin_template/staff_details.html
{% extends 'admin_template/admin_master.html' %}
{% block content %}
{% load static %}

<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8" style="margin-top: 4em;">
            <select class="form-select" aria-label="Default select example">
                <option selected>staff details</option>
                <option value="1">One</option>
              </select>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
<div class="container" style="margin-top: 5em;">
    <div class="row bg-white">
        <div class="col-md-6">
            <img src="..." alt="" style="width: 3em;">
        </div>
        <div class="col-md-6">
            <div class="my-5">
                <h2 class="my-5"></h2>
            </div>
        </div>
    </div>
</div>

{% endblock  %}